# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='link',
            field=models.CharField(default='-', max_length=128),
        ),
    ]
