# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0002_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='link',
        ),
    ]
